const personArray = [
    {"name":"Tyseer Aboulnasr", "URL":"Tyseer_Aboulnasr"},
    {"name":"Katya Echazarreta", "URL":"Katya_Echazarreta"},
    {"name":"Anna Grassellino", "URL":"Anna_Grassellino"},
    {"name":"Violet B. Haas", "URL":"Violet_B._Haas"},
    {"name":"Admela Jukan", "URL":"Admela_Jukan"},
    {"name":"Nora Stanton Barney", "URL":"Nora_Stanton_Barney"},
    {"name":"Mary Barra", "URL":"Mary_Barra"},
    {"name":"Edith Clarke", "URL":"Edith_Clarke"},
    {"name":"Olive Dennis", "URL":"Olive_Dennis"},
    {"name":"Denice Denton", "URL":"Denice_Denton"},
    {"name":"Mildred Dresselhaus", "URL":"Mildred_Dresselhaus"},
    {"name":"Bonnie J. Dunbar", "URL":"Bonnie_J._Dunbar"},
    {"name":"Thelma Estrin", "URL":"Thelma_Estrin"},
    {"name":"Bertha Lamme Feicht", "URL":"Bertha_Lamme_Feicht"},
    {"name":"Lillian Moller Gilbreth", "URL":"Lillian_Moller_Gilbreth"},
    {"name":"Lois Graham", "URL":"Lois_Graham"},
    {"name":"Beatrice Hicks", "URL":"Beatrice_Hicks"},
    {"name":"Grace Hopper", "URL":"Grace_Hopper"},
    {"name":"Paige Kassalen", "URL":"Paige_Kassalen"},
    {"name":"Barbara McClintock", "URL":"Barbara_McClintock"},
    {"name":"Mahta Moghaddam", "URL":"Mahta_Moghaddam"},
    {"name":"Frances Northcutt", "URL":"Frances_Northcutt"},
    {"name":"Elisabeth Paté-Cornell", "URL":"Elisabeth_Pate-Cornell"},
    {"name":"Judith Resnik", "URL":"Judith_Resnik"},
    {"name":"Ellen Swallow Richards", "URL":"Ellen_Swallow_Richards"},
    {"name":"Mary Golda Ross", "URL":"Mary_Golda_Ross"},
    {"name":"Nancy Deloye Fitzroy", "URL":"Nancy_Deloye_Fitzroy"},
    {"name":"Katherine Stinson", "URL":"Katherine_Stinson"},
    {"name":"Carlia S. Westcott","URL":"Carlia_S._Westcott"}
];
export default personArray;