const placeArray = [
    {"name":"The Grange", "URL":"The_Grange_(Paris,_Kentucky)"},
    {"name":"Burns United Methodist Church", "URL":"Burns_United_Methodist_Church"},
    {"name":"Antioch Missionary Baptist Church", "URL":"Antioch_Missionary_Baptist_Church"},
    {"name":"John Brown Farm State Historic Site", "URL":"John_Brown_Farm_State_Historic_Site"},
    {"name":"Harpers Ferry National Historical Park", "URL":"Harpers_Ferry_National_Historical_Park"},
    {"name":"Lawrence Experiment Station", "URL":"Lawrence_Experiment_Station"},
    {"name":"National Cancer Center", "URL":"National_Cancer_Center"},
    {"name":"National Institute of Population and Social Security Research", "URL":"National_Institute_of_Population_and_Social_Security_Research"},
    {"name":"Geospatial Information Authority of Japan", "URL":"Geospatial_Information_Authority_of_Japan"},
    {"name":"Center for International Forestry Research", "URL":"Center_for_International_Forestry_Research"},
    {"name":"Center for Tropical Forest Science", "URL":"Center_for_Tropical_Forest_Science"},
    {"name":"European Forest Institute", "URL":"European_Forest_Institute"},
    {"name":"International Union of Forest Research Organizations", "URL":"International_Union_of_Forest_Research_Organizations"},
    {"name":"Forestry Research Institute of Nigeria", "URL":"Forestry_Research_Institute_of_Nigeria"},
    {"name":"Forestry and Agricultural Biotechnology Institute", "URL":"Forestry_and_Agricultural_Biotechnology_Institute"},
    {"name":"International Livestock Research Institute", "URL":"International_Livestock_Research_Institute"},
    {"name":"Applied Physics Laboratory", "URL":"Applied_Physics_Laboratory"},
    {"name":"The Louvre", "URL":"Louvre"},
    {"name":"Vatican Museums", "URL":"Vatican_Museums"},
    {"name":"Natural History Museum", "URL":"Natural_History_Museum,_London"},
    {"name":"British Museum", "URL":"British_Museum"},
    {"name":"National Museum of Natural History", "URL":"National_Museum_of_Natural_History"},
    {"name":"Tate Modern", "URL":"Tate_Modern"},
    {"name":"National Museum of Korea", "URL":"National_Museum_of_Korea"},
    {"name":"Musée d'Orsay", "URL":"Musée_d%27Orsay"},
    {"name":"National Gallery of Art", "URL":"National_Gallery_of_Art"},
    {"name":"Metropolitan Museum of Art", "URL":"Metropolitan_Museum_of_Art"},
    {"name":"Centre Pompidou", "URL":"Centre_Pompidou"},
    {"name":"Southbank Centre", "URL":"Southbank_Centre"},
    {"name":"Hermitage Museum", "URL":"Hermitage_Museum"},
    {"name":"National Gallery", "URL":"National_Gallery"},
    {"name":"State Russian Museum", "URL":"Russian_Museum"},
    {"name":"Museo del Prado", "URL":"Museo_del_Prado"},
    {"name":"Victoria and Albert Museum", "URL":"Victoria_and_Albert_Museum"},
    {"name":"Somerset House", "URL":"Somerset_House"},
    {"name":"The Science Museum", "URL":"Science_Museum,_London"},
    {"name":"Galleria degli Uffizi", "URL":"Uffizi"},
    {"name":"Museum of Modern Art", "URL":"Museum_of_Modern_Art"},
    {"name":"M+", "URL":"M%2B"},
    {"name":"Cité des Sciences et de l'Industrie", "URL":"Cité_des_Sciences_et_de_l%27Industrie"},
    {"name":"National Museum of Scotland", "URL":"National_Museum_of_Scotland"},
    {"name":"Museum of Free Derry", "URL":"Museum_of_Free_Derry"},
    {"name":"National Air and Space Museum", "URL":"National_Air_and_Space_Museum"}
];
export default placeArray;